<a href="https://colab.research.google.com/github/imabari/ImabariScraping/blob/master/%E3%82%B1%E3%83%B3%E3%83%96%E3%83%AA%E3%83%83%E3%82%B8%E5%A4%A7%E5%AD%A6%E5%9B%B3%E6%9B%B8%E9%A4%A8%E6%89%80%E8%94%B5%E6%97%A5%E6%9C%AC%E5%8F%A4%E5%85%B8%E7%B1%8D%E3%81%AE%E6%9B%B8%E8%AA%8C%E6%83%85%E5%A0%B1%E3%81%AETEI_XML%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!wget "https://www.dhii.jp/dh/tei/cam_jp_xml.tgz"
!tar xvf cam_jp_xml.tgz

--2022-11-20 04:28:49--  https://www.dhii.jp/dh/tei/cam_jp_xml.tgz
Resolving www.dhii.jp (www.dhii.jp)... 121.119.247.132
Connecting to www.dhii.jp (www.dhii.jp)|121.119.247.132|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1695161 (1.6M) [application/x-gzip]
Saving to: ‘cam_jp_xml.tgz.3’

cam_jp_xml.tgz.3    100%[===================>]   1.62M  1.39MB/s    in 1.2s

2022-11-20 04:28:51 (1.39 MB/s) - ‘cam_jp_xml.tgz.3’ saved [1695161/1695161]

MS-FG-00710-00129.xml
MS-FG-00710-00133.xml
MS-FH-00711-00023.xml
MS-FH-00911-00038.xml
MS-FJ-00120-00036.xml
MS-FJ-00120-00387.xml
MS-FJ-00120-00397.xml
MS-FJ-00123-00014.xml
MS-FJ-00340-00001.xml
MS-FJ-00340-00002.xml
MS-FJ-00341-00002.xml
MS-FJ-00341-00004.xml
MS-FJ-00341-00007.xml
MS-FJ-00341-00008.xml
MS-FJ-00385-00040.xml
MS-FJ-00636-00017-00064.xml
MS-FJ-00645-00005.xml
MS-FJ-00709-00001.xml
MS-FJ-00709-00002.xml
MS-FJ-00709-00003.xml
MS-FJ-00709-00004.xml
MS-FJ-00709-00005.xml
MS-FJ-00709-00006.xml
MS-FJ-00709-00007.xml
MS-FJ-00709-00008.xml
MS-FJ-00709-00009.xml
MS-FJ-00709-00010.xml
MS-FJ-00709-00011.xml
MS-FJ-00709-00012.xml
MS-FJ-00709-00013.xml
MS-FJ-00709-00014.xml
MS-FJ-00709-00015.xml
MS-FJ-00709-00016.xml
MS-FJ-00709-00017.xml
MS-FJ-00709-00018.xml
MS-FJ-00709-00019.xml
MS-FJ-00709-00020.xml
MS-FJ-00709-00021.xml
MS-FJ-00709-00022.xml
MS-FJ-00732-00004.xml
MS-FJ-00734-00004.xml
MS-FJ-00740-00018-00002.xml
MS-FJ-00740-00018-00003.xml
MS-FJ-00740-00018-00004.xml
MS-FJ-00743-00001.xml
MS-FJ-00750-00001.xml
MS-FJ-00751-00001.xml
MS-FJ-00928-00002.xml
MS-FJ-00930-00006.xml
MS-FJ-00938-00003.xml
MS-FJ-00938-00004.xml
MS-FJ-00938-00005.xml
MS-FJ-00938-00010.xml
MS-FJ-00938-00011.xml
MS-FJ-00938-00014.xml
MS-FJ-00938-00015.xml
MS-FJ-00938-00023.xml
MS-FJ-00938-00024.xml
MS-FJ-00938-00029-00030.xml
MS-FJ-00960-00101.xml
MS-FJ-00960-00102.xml
MS-FJ-00962-00004.xml
MS-FJ-00973-00045.xml
MS-FJ-00973-00050.xml
MS-FJ-00973-00051.xml
MS-FJ-00978-00012.xml
MS-FJ-00980-00006.xml
MS-FJ-00980-00008.xml
MS-FJ-00980-00009.xml
MS-FJ-00983-00014.xml
MS-FJ-00997-00918.xml
MS-FJ-01000-00003.xml
MS-FJ-01000-00016.xml
MS-FJ-01000-00023.xml
MS-FJ-01000-00024.xml
MS-FJ-01000-00048.xml
MS-FL-02018-00009-00003.xml
PR-01889-00005-00001.xml
PR-01889-00005-00002.xml
PR-01889-00005-00003.xml
PR-01889-00005-00004.xml
PR-01889-00005-00005.xml
PR-01889-00005-00006.xml
PR-01889-00005-00007.xml
PR-01889-00005-00008.xml
PR-01889-00005-00009.xml
PR-01889-00005-00010.xml
PR-01889-00005-00011.xml
PR-01889-00005-00012.xml
PR-01889-00005-00013.xml
PR-01889-00005-00014.xml
PR-01889-00005-00015.xml
PR-01889-00005-00016.xml
PR-FA-00858-00020.xml
PR-FB-00195-00056.xml
PR-FB-00291-00022-00024.xml
PR-FB-00326-00023.xml
PR-FB-00326-00024.xml
PR-FB-00326-00037.xml
PR-FB-00349-00003.xml
PR-FB-00525-00014.xml
PR-FB-00525-00015.xml
PR-FB-00527-00009.xml
PR-FB-00547-00013.xml
PR-FB-00555-00003.xml
PR-FB-00557-00016.xml
PR-FB-00557-00017.xml
PR-FB-00557-00018.xml
PR-FB-00558-00028.xml
PR-FB-00558-00029.xml
PR-FB-00558-00030.xml
PR-FB-00558-00031-00032.xml
PR-FB-00563-00024.xml
PR-FB-00563-00025.xml
PR-FB-00563-00026-00028.xml
PR-FB-00565-00003.xml
PR-FB-00565-00004.xml
PR-FB-00565-00005.xml
PR-FB-00577-00009.xml
PR-FB-00580-00015-00016.xml
PR-FB-00584-00003.xml
PR-FB-00584-00004.xml
PR-FB-00584-00005.xml
PR-FB-00584-00006.xml
PR-FB-00584-00013.xml
PR-FB-00597-00002.xml
PR-FB-00597-00003.xml
PR-FB-00598-00001.xml
PR-FB-00598-00008.xml
PR-FB-00599-00012.xml
PR-FB-00616-00006.xml
PR-FB-00616-00007.xml
PR-FB-00724-00003.xml
PR-FB-00724-00022.xml
PR-FB-00745-00003.xml
PR-FB-00745-00078.xml
PR-FB-00759-00001.xml
PR-FB-00759-00002.xml
PR-FB-00769-00001.xml
PR-FB-00805-00002.xml
PR-FB-00886-00005-00006.xml
PR-FB-00997-00002.xml
PR-FB-00997-00008-00027.xml
PR-FG-00710-00021-00024.xml
PR-FG-00710-00108.xml
PR-FG-00710-00111.xml
PR-FG-00710-00118.xml
PR-FG-00710-00126.xml
PR-FG-00710-00127.xml
PR-FG-00710-00128.xml
PR-FG-00710-00130.xml
PR-FG-00710-00131.xml
PR-FG-00710-00134.xml
PR-FG-00710-00135.xml
PR-FG-00711-00048.xml
PR-FG-00711-00049.xml
PR-FG-00870.xml
PR-FH-00110-00025-00026.xml
PR-FH-00510-00127.xml
PR-FH-00510-00128.xml
PR-FH-00510-00129.xml
PR-FH-00710-00070.xml
PR-FH-00710-00071.xml
PR-FH-00710-00072.xml
PR-FH-00710-00075.xml
PR-FH-00911-00062.xml
PR-FJ-00104-00001.xml
PR-FJ-00105-00001.xml
PR-FJ-00106-00004.xml
PR-FJ-00113-00004.xml
PR-FJ-00113-00005.xml
PR-FJ-00113-00036.xml
PR-FJ-00113-00039-00040.xml
PR-FJ-00113-00074.xml
PR-FJ-00114-00015.xml
PR-FJ-00123-00017.xml
PR-FJ-00123-00020.xml
PR-FJ-00123-00022.xml
PR-FJ-00123-00023.xml
PR-FJ-00124-00021.xml
PR-FJ-00124-00022.xml
PR-FJ-00124-00023.xml
PR-FJ-00134-00001.xml
PR-FJ-00134-00002.xml
PR-FJ-00172-00001-00002.xml
PR-FJ-00176-00004.xml
PR-FJ-00185-00001.xml
PR-FJ-00185-00002.xml
PR-FJ-00185-00003.xml
PR-FJ-00185-00004.xml
PR-FJ-00185-00005.xml
PR-FJ-00185-00006.xml
PR-FJ-00185-00007.xml
PR-FJ-00185-00008.xml
PR-FJ-00185-00009.xml
PR-FJ-00185-00010.xml
PR-FJ-00185-00011.xml
PR-FJ-00185-00012.xml
PR-FJ-00185-00013.xml
PR-FJ-00185-00014.xml
PR-FJ-00185-00015.xml
PR-FJ-00185-00016.xml
PR-FJ-00185-00017.xml
PR-FJ-00185-00018.xml
PR-FJ-00185-00019.xml
PR-FJ-00185-00020.xml
PR-FJ-00190-00001-00001.xml
PR-FJ-00190-00001-00002.xml
PR-FJ-00190-00001-00003.xml
PR-FJ-00190-00001-00004.xml
PR-FJ-00190-00001-00005.xml
PR-FJ-00190-00001-00006.xml
PR-FJ-00190-00001-00007.xml
PR-FJ-00209-00012.xml
PR-FJ-00211-00006.xml
PR-FJ-00211-00007.xml
PR-FJ-00211-00008.xml
PR-FJ-00231-00010.xml
PR-FJ-00231-00011-00001.xml
PR-FJ-00231-00011-00002.xml
PR-FJ-00231-00012.xml
PR-FJ-00248-00012.xml
PR-FJ-00248-00016.xml
PR-FJ-00248-00017.xml
PR-FJ-00248-00018.xml
PR-FJ-00248-00019.xml
PR-FJ-00248-00020.xml
PR-FJ-00248-00021.xml
PR-FJ-00248-00022.xml
PR-FJ-00272-00006-00011.xml
PR-FJ-00343-00007.xml
PR-FJ-00343-00008.xml
PR-FJ-00343-00017.xml
PR-FJ-00343-00018.xml
PR-FJ-00343-00020.xml
PR-FJ-00355-00001.xml
PR-FJ-00355-00002.xml
PR-FJ-00357-00001.xml
PR-FJ-00390-00008.xml
PR-FJ-00463-00001.xml
PR-FJ-00463-00002.xml
PR-FJ-00463-00003.xml
PR-FJ-00463-00006.xml
PR-FJ-00467-00005.xml
PR-FJ-00467-00006.xml
PR-FJ-00467-00007.xml
PR-FJ-00467-00008.xml
PR-FJ-00467-00009.xml
PR-FJ-00467-00010.xml
PR-FJ-00467-00011.xml
PR-FJ-00467-00012.xml
PR-FJ-00467-00013.xml
PR-FJ-00467-00014.xml
PR-FJ-00467-00021.xml
PR-FJ-00467-00022.xml
PR-FJ-00467-00023.xml
PR-FJ-00467-00024.xml
PR-FJ-00467-00025.xml
PR-FJ-00467-00026.xml
PR-FJ-00467-00027.xml
PR-FJ-00467-00028.xml
PR-FJ-00468-00001.xml
PR-FJ-00468-00002.xml
PR-FJ-00469-00004.xml
PR-FJ-00471-00039.xml
PR-FJ-00474-00002.xml
PR-FJ-00485-00002.xml
PR-FJ-00489-00005.xml
PR-FJ-00489-00006.xml
PR-FJ-00490-00002.xml
PR-FJ-00490-00003.xml
PR-FJ-00490-00005.xml
PR-FJ-00490-00006.xml
PR-FJ-00490-00007.xml
PR-FJ-00490-00008.xml
PR-FJ-00490-00009-00010.xml
PR-FJ-00490-00011.xml
PR-FJ-00490-00012.xml
PR-FJ-00490-00013.xml
PR-FJ-00490-00014.xml
PR-FJ-00490-00015.xml
PR-FJ-00490-00016.xml
PR-FJ-00490-00017.xml
PR-FJ-00490-00020.xml
PR-FJ-00490-00021.xml
PR-FJ-00490-00022-00001.xml
PR-FJ-00499-00004.xml
PR-FJ-00501-00001.xml
PR-FJ-00501-00002.xml
PR-FJ-00501-00003.xml
PR-FJ-00502-00001.xml
PR-FJ-00512-00002.xml
PR-FJ-00512-00003.xml
PR-FJ-00515-00002.xml
PR-FJ-00515-00003.xml
PR-FJ-00515-00005.xml
PR-FJ-00515-00006.xml
PR-FJ-00521-00001.xml
PR-FJ-00521-00002.xml
PR-FJ-00521-00003.xml
PR-FJ-00521-00004.xml
PR-FJ-00540-00002-00001.xml
PR-FJ-00552-00001.xml
PR-FJ-00558-00001.xml
PR-FJ-00589-00003.xml
PR-FJ-00590-00001.xml
PR-FJ-00590-00002.xml
PR-FJ-00590-00003.xml
PR-FJ-00601-00001.xml
PR-FJ-00601-00002.xml
PR-FJ-00604-00001.xml
PR-FJ-00604-00002.xml
PR-FJ-00604-00003.xml
PR-FJ-00604-00004.xml
PR-FJ-00604-00005.xml
PR-FJ-00606-00003.xml
PR-FJ-00609-00001.xml
PR-FJ-00619-00030.xml
PR-FJ-00620-00001.xml
PR-FJ-00630-00001.xml
PR-FJ-00693-00001.xml
PR-FJ-00696-00005-00011.xml
PR-FJ-00696-00005-00012.xml
PR-FJ-00696-00005-00013.xml
PR-FJ-00701-00002.xml
PR-FJ-00707-00001.xml
PR-FJ-00707-00002.xml
PR-FJ-00707-00003.xml
PR-FJ-00707-00004.xml
PR-FJ-00707-00005.xml
PR-FJ-00707-00006.xml
PR-FJ-00707-00007.xml
PR-FJ-00707-00008.xml
PR-FJ-00709-00025.xml
PR-FJ-00709-00026.xml
PR-FJ-00709-00027.xml
PR-FJ-00709-00028.xml
PR-FJ-00709-00029.xml
PR-FJ-00709-00030.xml
PR-FJ-00709-00031.xml
PR-FJ-00709-00032.xml
PR-FJ-00709-00033.xml
PR-FJ-00709-00034.xml
PR-FJ-00709-00035.xml
PR-FJ-00713-00002.xml
PR-FJ-00715-00005.xml
PR-FJ-00715-00006.xml
PR-FJ-00715-00007.xml
PR-FJ-00715-00008.xml
PR-FJ-00715-00009.xml
PR-FJ-00715-00010.xml
PR-FJ-00715-00011.xml
PR-FJ-00720-00002.xml
PR-FJ-00722-00002-00004.xml
PR-FJ-00722-00002-00005.xml
PR-FJ-00722-00002-00006.xml
PR-FJ-00722-00008.xml
PR-FJ-00723-00004.xml
PR-FJ-00723-00005.xml
PR-FJ-00723-00006.xml
PR-FJ-00732-00001.xml
PR-FJ-00732-00003.xml
PR-FJ-00732-00005-00006.xml
PR-FJ-00733-00009.xml
PR-FJ-00734-00005.xml
PR-FJ-00734-00006-00007.xml
PR-FJ-00734-00016-00017.xml
PR-FJ-00734.xml
PR-FJ-00737-00007.xml
PR-FJ-00737-00026.xml
PR-FJ-00740-00009-00016.xml
PR-FJ-00740-00033.xml
PR-FJ-00740-00034.xml
PR-FJ-00744-00002.xml
PR-FJ-00744-00003.xml
PR-FJ-00744-00004.xml
PR-FJ-00744-00005.xml
PR-FJ-00744-00006.xml
PR-FJ-00744-00007.xml
PR-FJ-00744-00008.xml
PR-FJ-00744-00009.xml
PR-FJ-00744-00010.xml
PR-FJ-00744-00011.xml
PR-FJ-00744-00012.xml
PR-FJ-00744-00013.xml
PR-FJ-00746-00001.xml
PR-FJ-00746-00002.xml
PR-FJ-00746-00031-00033.xml
PR-FJ-00746-00038.xml
PR-FJ-00754-00002.xml
PR-FJ-00755-00002.xml
PR-FJ-00755-00003.xml
PR-FJ-00756-00001.xml
PR-FJ-00757-00007.xml
PR-FJ-00758-00004.xml
PR-FJ-00759-00002.xml
PR-FJ-00760-00007.xml
PR-FJ-00760-00008.xml
PR-FJ-00761-00004.xml
PR-FJ-00762-00003.xml
PR-FJ-00764-00007.xml
PR-FJ-00764-00009.xml
PR-FJ-00764-00023.xml
PR-FJ-00764-00047.xml
PR-FJ-00764-00057.xml
PR-FJ-00766-00008.xml
PR-FJ-00766-00009.xml
PR-FJ-00767-00004.xml
PR-FJ-00767-00005-00006.xml
PR-FJ-00768-00009.xml
PR-FJ-00769-00013.xml
PR-FJ-00769-00016.xml
PR-FJ-00769-00017.xml
PR-FJ-00770-00001.xml
PR-FJ-00770-00003.xml
PR-FJ-00770-00004.xml
PR-FJ-00770-00016-00017.xml
PR-FJ-00770-00034.xml
PR-FJ-00814-00042-00043.xml
PR-FJ-00814-00053.xml
PR-FJ-00814-00056.xml
PR-FJ-00836-00036.xml
PR-FJ-00867-00004-00004-00006.xml
PR-FJ-00867-00004-00011.xml
PR-FJ-00867-00004-00012.xml
PR-FJ-00867-00004-00013.xml
PR-FJ-00867-00006-00005.xml
PR-FJ-00877-00045.xml
PR-FJ-00919-00016-00001-00002.xml
PR-FJ-00921-00018.xml
PR-FJ-00924-00002.xml
PR-FJ-00924-00003.xml
PR-FJ-00924-00004.xml
PR-FJ-00924-00005.xml
PR-FJ-00924-00006.xml
PR-FJ-00924-00007-00008.xml
PR-FJ-00927-00001-00002.xml
PR-FJ-00928-00003.xml
PR-FJ-00928-00004.xml
PR-FJ-00938-00006.xml
PR-FJ-00938-00013.xml
PR-FJ-00938-00019.xml
PR-FJ-00938-00020.xml
PR-FJ-00938-00021.xml
PR-FJ-00938-00022.xml
PR-FJ-00957-00003.xml
PR-FJ-00961-00034.xml
PR-FJ-00961-00036.xml
PR-FJ-00961-00095.xml
PR-FJ-00962-00005.xml
PR-FJ-00970.xml
PR-FJ-00972-00010.xml
PR-FJ-00972-00011.xml
PR-FJ-00973-00043.xml
PR-FJ-00973-00044.xml
PR-FJ-00973-00049.xml
PR-FJ-00977-00004.xml
PR-FJ-00977-00018.xml
PR-FJ-00980-00007.xml
PR-FJ-01000-00012.xml
PR-FJ-01000-00015.xml
PR-FJ-01000-00017.xml
PR-WADDLETON-B-00021-00005.xml

In [2]:
!mkdir cam_jp_xml
!mv *.xml cam_jp_xml

mkdir: cannot create directory ‘cam_jp_xml’: File exists

In [3]:
from lxml import etree
import pathlib

In [4]:
import pandas as pd

In [5]:
import numpy as np

In [6]:
ns = {"tei": "http://www.tei-c.org/ns/1.0", "xml": "http://www.w3.org/XML/1998/namespace"}

In [7]:
parser = etree.XMLParser(recover=True)

In [8]:
def strjoin(s, w = " "):

    if s:
        result = w.join([" ".join([j for j in i.split() if j]) for i in s])

        return result
    
    else:
        return ""

# タイトルを一覧表示

In [9]:
result = []

for p in pathlib.Path("cam_jp_xml").glob("*.xml"):

    tree = etree.parse(p, parser)
    root = tree.getroot()

    title = strjoin(root.xpath("//tei:teiHeader//tei:title/text()", namespaces=ns), "/")

    result.append({"file": str(p), "title": title})

In [10]:
df = pd.DataFrame(result)
df

,file,title
0,cam_jp_xml/PR-FJ-00744-00005.xml,FJ.744.5/Heike Monogatari/平家物語
1,cam_jp_xml/PR-FJ-00490-00014.xml,FJ.490.14/Kotoba no yachikusa/詞のやちくさ
2,cam_jp_xml/PR-FB-00997-00008-00027.xml,FB.997.8-27/Bubishi/武備志
3,cam_jp_xml/PR-01889-00005-00012.xml,1889.5.12/The cub's triumph/Kitsune no Tegara
4,cam_jp_xml/MS-FJ-01000-00023.xml,FJ.1000.23/Suehirogari/末ひろかり/The unfolding of ...
...,...,...
458,cam_jp_xml/PR-FJ-00463-00003.xml,FJ.463.3/Agatai zatsuroku hoshō/県居雑録補抄
459,cam_jp_xml/MS-FJ-00120-00036.xml,FJ.120.36/Eiri Edo ōezu/ゑ入江戸大絵図
460,cam_jp_xml/MS-FJ-00734-00004.xml,FJ.734.4/Ise Monogatari/伊勢物語
461,cam_jp_xml/PR-FJ-00715-00010.xml,FJ.715.10/Harada Jirō Tadanao/原田次郎種直
462,cam_jp_xml/PR-FJ-00190-00001-00004.xml,FJ.190.1.4/Bankoku Kōhō Reikan/万国公法蠡管

# 綴じ方の情報を見てみる

In [11]:
result = []

for p in pathlib.Path("cam_jp_xml").glob("*.xml"):

    tree = etree.parse(p, parser)
    root = tree.getroot()

    for i in root.xpath("//tei:bindingDesc", namespaces=ns):

        binding = i.xpath("./tei:p/text()", namespaces=ns)[0]
        title = strjoin(i.xpath("//tei:title/text()", namespaces=ns), "/")

        result.append({"binding": binding, "title": title})

In [12]:
df = pd.DataFrame(result)
df

,binding,title
0,Kansu-bon 巻子本 (scroll),FJ.1000.23/Suehirogari/末ひろかり/The unfolding of ...
1,Kansu-bon 巻子本 (scroll),FJ.1000.16/Shinobugusa/忍ふ艸/Materials which may...
2,Orihon 折本 (concertina book),FG.711.49/Daihannya hatamitakyō (Dabore boluom...
3,Fukurotoji袋綴 (’bag’ binding),FJ.734.2-3/Ise monogatari/伊勢物語 (外題)/The tales ...
4,Fukurotoji袋綴 (’bag’ binding).,FJ.961.95 (3-5)/Zōho ukiyoe ruikō/増補浮世絵類考 (外題)...
5,Fukurotoji袋綴 (’bag’ binding),FJ.970.10-15/Oumajirushi/御馬印 (目録題)/Horse banne...
6,Kansu-bon 巻子本 (scroll),FJ.1000.17/Ryūkyūjin gyōretsu/琉球人行列 (仮題)/Proce...
7,Kansu-bon 巻子本 (scroll),FJ.1000.12/Fumoto no chiri/麓の塵 (序文)/Dusts whic...
8,Detchōsō 粘葉装,FG.711.48/Daibirushana jōbutsukyō sho/大毘盧舎那成仏経...
9,Kansu-bon 巻子本 (scroll),FJ.1000.15/Hanjimono/はんじもの (外題)/Puzzles
10,"Hōhaisō 包背装, detchōsō 粘葉装",FG.710.135/Shaku makaenron san gensho/釈摩訶衍論賛玄疏...
11,Kansu-bon 巻子本 (scroll),"FJ.1000.3/Myōhō rengekyō/妙法蓮華経/Lotus Sutra, Sa..."
12,Originally kansu-bon 巻子本 (emaki 絵巻) which has ...,FJ.960.102/Nezumi no sōshi/鼠のさうし (外題)/The tale...
13,Fukurotoji 袋綴 (’bag’ binding).,FJ.390.8/Zenrin kokuhō kōki/善隣国宝後記 (外題)/Later ...

# 書籍の形についての情報

In [13]:
result = []

for p in pathlib.Path("cam_jp_xml").glob("*.xml"):

    tree = etree.parse(p, parser)
    root = tree.getroot()

    for i in root.xpath("//tei:teiHeader/tei:fileDesc", namespaces=ns):

        title = strjoin(i.xpath(".//tei:title[@type='uniform']/text()", namespaces=ns))
        binds = strjoin(i.xpath(".//tei:bindingDesc/tei:p/text()", namespaces=ns))
        extent = strjoin(i.xpath(".//tei:extent/descendant::text()", namespaces=ns))

        result.append({"title": title, "binds": binds, "extent": extent})

In [14]:
df = pd.DataFrame(result)
df

                 title                   binds                  extent
0                 平家物語                                      13巻12冊; 大本
1               詞のやちくさ                                    3冊(不分巻); 半紙本
2                  武備志                                         40冊; 大本
3    Kitsune no Tegara                                         1冊; 縮緬本
4                末ひろかり  Kansu-bon 巻子本 (scroll)  1 jiku 軸  330  10740
..                 ...                     ...                     ...
458             県居雑録補抄                                          1冊; 大本
459            ゑ入江戸大絵図                            図1舗; 140.3cmx141.6cm
460               伊勢物語                                         1冊; 半紙本
461             原田次郎種直                                       5段1冊; 半紙本
462             万国公法蠡管                                        7編7冊; 大本

[463 rows x 3 columns]

# 書籍の形状をカウントしてみる

In [15]:
result = []

for p in pathlib.Path("cam_jp_xml").glob("*.xml"):

    tree = etree.parse(p, parser)
    root = tree.getroot()

    extent = strjoin(root.xpath("//tei:physDesc//tei:extent/text()", namespaces=ns))

    result.append({"extent": extent})

In [16]:
df0 = pd.DataFrame(result)
df0

                   extent
0              13巻12冊; 大本
1            3冊(不分巻); 半紙本
2                 40冊; 大本
3                 1冊; 縮緬本
4               1 jiku 軸
..                    ...
458                1冊; 大本
459  図1舗; 140.3cmx141.6cm
460               1冊; 半紙本
461             5段1冊; 半紙本
462              7編7冊; 大本

[463 rows x 1 columns]

In [17]:
df1 = df0["extent"].str.extract(";(?P<size>.+)$",expand=True)
df1["size"] = df1["size"].str.strip()

In [18]:
df1["size"].value_counts().reset_index()

                     index  size
0                       大本   271
1                      半紙本   108
2                      縮緬本    16
3                       中本    10
4                       折本     7
5                       横本     4
6                       半紙     2
7                        中     2
8                      特大本     2
9                       小本     2
10                     四六判     1
11           25.6cm×17.8cm     1
12  scroll: 1400mm X 460mm     1
13  26 cm [27 cm as bound]     1
14        25.5 cm x 297 cm     1
15                  26 cm.     1
16          87.7cmx153.8cm     1
17                   25cm.     1
18                      横小     1
19           168cmx125.2cm     1
20                   27 cm     1
21                  23 cm.     1
22              中 (chūbon)     1
23         140.3cmx141.6cm     1

# 来歴情報に登場する人名を見てみる

In [19]:
result = []

for p in pathlib.Path("cam_jp_xml").glob("*.xml"):

    tree = etree.parse(p, parser)
    root = tree.getroot()

    for i in root.xpath("//tei:teiHeader/tei:fileDesc", namespaces=ns):

        title = strjoin(i.xpath(".//tei:title/text()", namespaces=ns), "/")
        name = strjoin(i.xpath(".//tei:provenance//tei:persName[@type='standard']/text()", namespaces=ns), "/")

        if name:
            result.append({"name": name, "title": title})

In [20]:
df = pd.DataFrame(result)
df

,name,title
0,"Aston, William George, 1841-1911/Satow, Ernest...",FJ.744.5/Heike Monogatari/平家物語
1,"Aston, William George, 1841-1911/Satow, Ernest...",FJ.490.14/Kotoba no yachikusa/詞のやちくさ
2,"Lockhart, James H. Stewart (James Haldane Stew...",FB.997.8-27/Bubishi/武備志
3,"Aston, William George, 1841-1911",FJ.1000.23/Suehirogari/末ひろかり/The unfolding of ...
4,"Aston, William George, 1841-1911",FJ.720.2/Ehon Sakaegusa/(戯場風俗）絵本栄家種/(Shibai fū...
...,...,...
393,"Aston, William George, 1841-1911/Satow, Ernest...",FJ.467.24/Meibutsu Rokucho/名物六帖
394,"Aston, William George, 1841-1911/Satow, Ernest...",FJ.463.3/Agatai zatsuroku hoshō/県居雑録補抄
395,"Aston, William George, 1841-1911",FJ.120.36/Eiri Edo ōezu/ゑ入江戸大絵図
396,"Aston, William George, 1841-1911",FJ.734.4/Ise Monogatari/伊勢物語
397,"Aston, William George, 1841-1911",FJ.715.10/Harada Jirō Tadanao/原田次郎種直

# 人ごとに、来歴として関与したタイトルをまとめて数えてみる

In [21]:
result = []

for p in pathlib.Path("cam_jp_xml").glob("*.xml"):

    tree = etree.parse(p, parser)
    root = tree.getroot()

    for i in root.xpath("//tei:teiHeader/tei:fileDesc", namespaces=ns):

        title = strjoin(i.xpath(".//tei:title[@type='uniform']/text()", namespaces=ns), "/")
        
        for j in i.xpath(".//tei:provenance//tei:persName[@type='standard']/text()", namespaces=ns):

            name = " ".join(j.split())
            result.append({"name": name, "title": title})

In [22]:
df = pd.DataFrame(result)
df

                                                  name    title
0                     Aston, William George, 1841-1911     平家物語
1                       Satow, Ernest Mason, 1843-1929     平家物語
2                     Aston, William George, 1841-1911   詞のやちくさ
3                       Satow, Ernest Mason, 1843-1929   詞のやちくさ
4    Lockhart, James H. Stewart (James Haldane Stew...      武備志
..                                                 ...      ...
602                   Aston, William George, 1841-1911   県居雑録補抄
603                     Satow, Ernest Mason, 1843-1929   県居雑録補抄
604                   Aston, William George, 1841-1911  ゑ入江戸大絵図
605                   Aston, William George, 1841-1911     伊勢物語
606                   Aston, William George, 1841-1911   原田次郎種直

[607 rows x 2 columns]

In [23]:
df["name"].value_counts()

Aston, William George, 1841-1911                                      337
Satow, Ernest Mason, 1843-1929                                        203
Lockhart, James H. Stewart (James Haldane Stewart), Sir, 1858-1937     38
Siebold, Heinrich von, 1852-1908                                       25
Morikawa, Kanʼichirō, 1887-1980                                        1
Ceadel, Eric B.                                                         1
Hawley, Frank, 1906-1961                                                1
Minns, Ellis H.                                                         1
Name: name, dtype: int64

# 人毎に、書名をリストしてみる

In [24]:
df.groupby(["name"])["title"].apply(list)

name
Aston, William George, 1841-1911                                      [平家物語, 詞のやちくさ, 末ひろかり, (戯場風俗）絵本栄家種, 詞通路, 和名類聚抄,...
Ceadel, Eric B.                                                                                                [百万塔陀羅尼]
Hawley, Frank, 1906-1961                                                                                     [釈摩訶衍論賛玄疏]
Lockhart, James H. Stewart (James Haldane Stewart), Sir, 1858-1937    [武備志, 司馬文正公伝家集選, 杜律集解, 唐詩正声, 古文真宝後集, 誠意伯詩抄, 続唐...
Minns, Ellis H.                                                                                          [豊臣秀吉朱印状 (仮題)]
Morikawa, Kanʼichirō, 1887-1980                                                                                [興福寺文書]
Satow, Ernest Mason, 1843-1929                                        [平家物語, 詞のやちくさ, 詞通路, [広重戯画], 和名類聚抄, 伊勢物語, 東海道敵討...
Siebold, Heinrich von, 1852-1908                                      [古銭価附, (新校正) 孔方図鑑, 蕃談, さころも, 浪花夢物語, 蔵泉記, (新校正)...
Name: title, dtype: object

# 人毎に、作成・刊行年をなるべくまとめてみる

In [25]:
result = []

for p in pathlib.Path("cam_jp_xml").glob("*.xml"):

    tree = etree.parse(p, parser)
    root = tree.getroot()

    for i in root.xpath("//tei:teiHeader/tei:fileDesc", namespaces=ns):

        title = strjoin(i.xpath(".//tei:title[@type='uniform']/text()", namespaces=ns), "/")
        origdate = i.xpath(".//tei:history//tei:origDate", namespaces=ns)[0].get("from", "").strip()

        for j in i.xpath(".//tei:provenance//tei:persName[@type='standard']/text()", namespaces=ns):

            name = " ".join(j.split())
            result.append({"name": name, "title": title, "origdate": origdate})

In [26]:
df0 = pd.DataFrame(result)
df0

                                                  name    title origdate
0                     Aston, William George, 1841-1911     平家物語
1                       Satow, Ernest Mason, 1843-1929     平家物語
2                     Aston, William George, 1841-1911   詞のやちくさ     1798
3                       Satow, Ernest Mason, 1843-1929   詞のやちくさ     1798
4    Lockhart, James H. Stewart (James Haldane Stew...      武備志     1664
..                                                 ...      ...      ...
602                   Aston, William George, 1841-1911   県居雑録補抄     1812
603                     Satow, Ernest Mason, 1843-1929   県居雑録補抄     1812
604                   Aston, William George, 1841-1911  ゑ入江戸大絵図     1688
605                   Aston, William George, 1841-1911     伊勢物語
606                   Aston, William George, 1841-1911   原田次郎種直     1671

[607 rows x 3 columns]

In [27]:
df1 = df0.groupby(["name", "origdate"])["origdate"].count().reset_index(name="count")
df1

                                 name origdate  count
0    Aston, William George, 1841-1911              92
1    Aston, William George, 1841-1911     1533      1
2    Aston, William George, 1841-1911     1580      1
3    Aston, William George, 1841-1911     1603      1
4    Aston, William George, 1841-1911     1608      1
..                                ...      ...    ...
240  Siebold, Heinrich von, 1852-1908     1821      1
241  Siebold, Heinrich von, 1852-1908     1826      1
242  Siebold, Heinrich von, 1852-1908     1841      1
243  Siebold, Heinrich von, 1852-1908     1853      1
244  Siebold, Heinrich von, 1852-1908     1868      1

[245 rows x 3 columns]

In [28]:
print(df1.to_csv())

,name,origdate,count
0,"Aston, William George, 1841-1911",,92
1,"Aston, William George, 1841-1911",1533,1
2,"Aston, William George, 1841-1911",1580,1
3,"Aston, William George, 1841-1911",1603,1
4,"Aston, William George, 1841-1911",1608,1
5,"Aston, William George, 1841-1911",1617,10
6,"Aston, William George, 1841-1911",1642,1
7,"Aston, William George, 1841-1911",1648,20
8,"Aston, William George, 1841-1911",1652,1
9,"Aston, William George, 1841-1911",1654,1
10,"Aston, William George, 1841-1911",1656,1
11,"Aston, William George, 1841-1911",1657,5
12,"Aston, William George, 1841-1911",1659,2
13,"Aston, William George, 1841-1911",1661,2
14,"Aston, William George, 1841-1911",1662,1
15,"Aston, William George, 1841-1911",1669,1
16,"Aston, William George, 1841-1911",1671,2
17,"Aston, William George, 1841-1911",1673,1
18,"Aston, William George, 1841-1911",1685,1
19,"Aston, William George, 1841-1911",1686,1
20,"Aston, William George, 1841-1911",1688,5
21,"Aston, William George, 1841-1911",1692,1
22,"Aston, William George, 1841-1911",1696,2
23,"Aston, William George, 1841-1911",1698,2
24,"Aston, William George, 1841-1911",1699,3
25,"Aston, William George, 1841-1911",1700,1
26,"Aston, William George, 1841-1911",1701,3
27,"Aston, William George, 1841-1911",1702,1
28,"Aston, William George, 1841-1911",1705,1
29,"Aston, William George, 1841-1911",1706,1
30,"Aston, William George, 1841-1911",1707,1
31,"Aston, William George, 1841-1911",1708,1
32,"Aston, William George, 1841-1911",1710,1
33,"Aston, William George, 1841-1911",1714,2
34,"Aston, William George, 1841-1911",1715,1
35,"Aston, William George, 1841-1911",1716,1
36,"Aston, William George, 1841-1911",1717,2
37,"Aston, William George, 1841-1911",1718,2
38,"Aston, William George, 1841-1911",1723,4
39,"Aston, William George, 1841-1911",1724,1
40,"Aston, William George, 1841-1911",1727,2
41,"Aston, William George, 1841-1911",1728,1
42,"Aston, William George, 1841-1911",1730,1
43,"Aston, William George, 1841-1911",1733,1
44,"Aston, William George, 1841-1911",1734,1
45,"Aston, William George, 1841-1911",1747,1
46,"Aston, William George, 1841-1911",1750,4
47,"Aston, William George, 1841-1911",1751,1
48,"Aston, William George, 1841-1911",1755,4
49,"Aston, William George, 1841-1911",1756,1
50,"Aston, William George, 1841-1911",1763,1
51,"Aston, William George, 1841-1911",1764,1
52,"Aston, William George, 1841-1911",1765,1
53,"Aston, William George, 1841-1911",1767,1
54,"Aston, William George, 1841-1911",1770,2
55,"Aston, William George, 1841-1911",1771,3
56,"Aston, William George, 1841-1911",1774,2
57,"Aston, William George, 1841-1911",1776,2
58,"Aston, William George, 1841-1911",1777,1
59,"Aston, William George, 1841-1911",1781,3
60,"Aston, William George, 1841-1911",1784,1
61,"Aston, William George, 1841-1911",1785,4
62,"Aston, William George, 1841-1911",1789,2
63,"Aston, William George, 1841-1911",1790,2
64,"Aston, William George, 1841-1911",1792,1
65,"Aston, William George, 1841-1911",1793,2
66,"Aston, William George, 1841-1911",1794,3
67,"Aston, William George, 1841-1911",1798,2
68,"Aston, William George, 1841-1911",1799,4
69,"Aston, William George, 1841-1911",1802,3
70,"Aston, William George, 1841-1911",1803,1
71,"Aston, William George, 1841-1911",1804,2
72,"Aston, William George, 1841-1911",1805,1
73,"Aston, William George, 1841-1911",1808,4
74,"Aston, William George, 1841-1911",1809,2
75,"Aston, William George, 1841-1911",1811,1
76,"Aston, William George, 1841-1911",1812,1
77,"Aston, William George, 1841-1911",1816,3
78,"Aston, William George, 1841-1911",1818,3
79,"Aston, William George, 1841-1911",1819,2
80,"Aston, William George, 1841-1911",1820,2
81,"Aston, William George, 1841-1911",1822,1
82,"Aston, William George, 1841-1911",1826,1
83,"Aston, William George, 1841-1911",1827,1
84,"Aston, William George, 1841-1911",1828,5
85,"Aston, William George, 1841-1911",1831,5
86,"Aston, William George, 1841-1911",1832,1
87,"Aston, William George, 1841-1911",1833,4
88,"Aston, William George, 1841-1911",1836,3
89,"Aston, William George, 1841-1911",1837,2
90,"Aston, William George, 1841-1911",1839,1
91,"Aston, William George, 1841-1911",1841,3
92,"Aston, William George, 1841-1911",1842,2
93,"Aston, William George, 1841-1911",1843,1
94,"Aston, William George, 1841-1911",1844,2
95,"Aston, William George, 1841-1911",1845,3
96,"Aston, William George, 1841-1911",1847,1
97,"Aston, William George, 1841-1911",1848,1
98,"Aston, William George, 1841-1911",1850,1
99,"Aston, William George, 1841-1911",1851,1
100,"Aston, William George, 1841-1911",1852,1
101,"Aston, William George, 1841-1911",1853,5
102,"Aston, William George, 1841-1911",1855,2
103,"Aston, William George, 1841-1911",1856,1
104,"Aston, William George, 1841-1911",1858,1
105,"Aston, William George, 1841-1911",1860,7
106,"Aston, William George, 1841-1911",1862,1
107,"Aston, William George, 1841-1911",1863,1
108,"Aston, William George, 1841-1911",1866,1
109,"Aston, William George, 1841-1911",1868,3
110,"Aston, William George, 1841-1911",1870,1
111,"Aston, William George, 1841-1911",1872,3
112,"Aston, William George, 1841-1911",1874,3
113,"Aston, William George, 1841-1911",1878,4
114,"Aston, William George, 1841-1911",1886,1
115,"Aston, William George, 1841-1911",1889,1
116,"Ceadel, Eric B.",0764,1
117,"Hawley, Frank, 1906-1961",1288,1
118,"Lockhart, James H. Stewart (James Haldane Stewart), Sir, 1858-1937",,9
119,"Lockhart, James H. Stewart (James Haldane Stewart), Sir, 1858-1937",1664,1
120,"Lockhart, James H. Stewart (James Haldane Stewart), Sir, 1858-1937",1696,2
121,"Lockhart, James H. Stewart (James Haldane Stewart), Sir, 1858-1937",1747,1
122,"Lockhart, James H. Stewart (James Haldane Stewart), Sir, 1858-1937",1755,1
123,"Lockhart, James H. Stewart (James Haldane Stewart), Sir, 1858-1937",1781,1
124,"Lockhart, James H. Stewart (James Haldane Stewart), Sir, 1858-1937",1790,4
125,"Lockhart, James H. Stewart (James Haldane Stewart), Sir, 1858-1937",1795,1
126,"Lockhart, James H. Stewart (James Haldane Stewart), Sir, 1858-1937",1801,1
127,"Lockhart, James H. Stewart (James Haldane Stewart), Sir, 1858-1937",1804,1
128,"Lockhart, James H. Stewart (James Haldane Stewart), Sir, 1858-1937",1808,1
129,"Lockhart, James H. Stewart (James Haldane Stewart), Sir, 1858-1937",1811,2
130,"Lockhart, James H. Stewart (James Haldane Stewart), Sir, 1858-1937",1826,1
131,"Lockhart, James H. Stewart (James Haldane Stewart), Sir, 1858-1937",1827,1
132,"Lockhart, James H. Stewart (James Haldane Stewart), Sir, 1858-1937",1828,1
133,"Lockhart, James H. Stewart (James Haldane Stewart), Sir, 1858-1937",1839,1
134,"Lockhart, James H. Stewart (James Haldane Stewart), Sir, 1858-1937",1843,3
135,"Lockhart, James H. Stewart (James Haldane Stewart), Sir, 1858-1937",1844,1
136,"Lockhart, James H. Stewart (James Haldane Stewart), Sir, 1858-1937",1848,1
137,"Lockhart, James H. Stewart (James Haldane Stewart), Sir, 1858-1937",1850,1
138,"Lockhart, James H. Stewart (James Haldane Stewart), Sir, 1858-1937",1851,1
139,"Lockhart, James H. Stewart (James Haldane Stewart), Sir, 1858-1937",1853,1
140,"Lockhart, James H. Stewart (James Haldane Stewart), Sir, 1858-1937",1904,1
141,"Minns, Ellis H.",1598,1
142,"Morikawa, Kanʼichirō, 1887-1980",1256,1
143,"Satow, Ernest Mason, 1843-1929",,65
144,"Satow, Ernest Mason, 1843-1929",1603,1
145,"Satow, Ernest Mason, 1843-1929",1608,1
146,"Satow, Ernest Mason, 1843-1929",1617,10
147,"Satow, Ernest Mason, 1843-1929",1652,1
148,"Satow, Ernest Mason, 1843-1929",1654,1
149,"Satow, Ernest Mason, 1843-1929",1657,1
150,"Satow, Ernest Mason, 1843-1929",1659,1
151,"Satow, Ernest Mason, 1843-1929",1661,1
152,"Satow, Ernest Mason, 1843-1929",1662,1
153,"Satow, Ernest Mason, 1843-1929",1669,1
154,"Satow, Ernest Mason, 1843-1929",1671,1
155,"Satow, Ernest Mason, 1843-1929",1673,2
156,"Satow, Ernest Mason, 1843-1929",1686,1
157,"Satow, Ernest Mason, 1843-1929",1688,2
158,"Satow, Ernest Mason, 1843-1929",1692,1
159,"Satow, Ernest Mason, 1843-1929",1696,2
160,"Satow, Ernest Mason, 1843-1929",1698,1
161,"Satow, Ernest Mason, 1843-1929",1699,3
162,"Satow, Ernest Mason, 1843-1929",1701,1
163,"Satow, Ernest Mason, 1843-1929",1702,1
164,"Satow, Ernest Mason, 1843-1929",1705,1
165,"Satow, Ernest Mason, 1843-1929",1714,1
166,"Satow, Ernest Mason, 1843-1929",1716,1
167,"Satow, Ernest Mason, 1843-1929",1717,1
168,"Satow, Ernest Mason, 1843-1929",1727,2
169,"Satow, Ernest Mason, 1843-1929",1728,1
170,"Satow, Ernest Mason, 1843-1929",1730,1
171,"Satow, Ernest Mason, 1843-1929",1733,1
172,"Satow, Ernest Mason, 1843-1929",1747,1
173,"Satow, Ernest Mason, 1843-1929",1751,1
174,"Satow, Ernest Mason, 1843-1929",1755,4
175,"Satow, Ernest Mason, 1843-1929",1756,1
176,"Satow, Ernest Mason, 1843-1929",1763,1
177,"Satow, Ernest Mason, 1843-1929",1764,1
178,"Satow, Ernest Mason, 1843-1929",1771,3
179,"Satow, Ernest Mason, 1843-1929",1774,2
180,"Satow, Ernest Mason, 1843-1929",1776,1
181,"Satow, Ernest Mason, 1843-1929",1777,1
182,"Satow, Ernest Mason, 1843-1929",1784,1
183,"Satow, Ernest Mason, 1843-1929",1785,2
184,"Satow, Ernest Mason, 1843-1929",1789,1
185,"Satow, Ernest Mason, 1843-1929",1790,2
186,"Satow, Ernest Mason, 1843-1929",1793,2
187,"Satow, Ernest Mason, 1843-1929",1798,2
188,"Satow, Ernest Mason, 1843-1929",1799,2
189,"Satow, Ernest Mason, 1843-1929",1802,3
190,"Satow, Ernest Mason, 1843-1929",1803,1
191,"Satow, Ernest Mason, 1843-1929",1804,1
192,"Satow, Ernest Mason, 1843-1929",1805,1
193,"Satow, Ernest Mason, 1843-1929",1808,1
194,"Satow, Ernest Mason, 1843-1929",1809,1
195,"Satow, Ernest Mason, 1843-1929",1811,1
196,"Satow, Ernest Mason, 1843-1929",1812,1
197,"Satow, Ernest Mason, 1843-1929",1816,2
198,"Satow, Ernest Mason, 1843-1929",1818,1
199,"Satow, Ernest Mason, 1843-1929",1819,2
200,"Satow, Ernest Mason, 1843-1929",1820,2
201,"Satow, Ernest Mason, 1843-1929",1822,1
202,"Satow, Ernest Mason, 1843-1929",1827,1
203,"Satow, Ernest Mason, 1843-1929",1828,3
204,"Satow, Ernest Mason, 1843-1929",1833,1
205,"Satow, Ernest Mason, 1843-1929",1834,1
206,"Satow, Ernest Mason, 1843-1929",1836,3
207,"Satow, Ernest Mason, 1843-1929",1837,1
208,"Satow, Ernest Mason, 1843-1929",1839,1
209,"Satow, Ernest Mason, 1843-1929",1841,1
210,"Satow, Ernest Mason, 1843-1929",1842,1
211,"Satow, Ernest Mason, 1843-1929",1845,2
212,"Satow, Ernest Mason, 1843-1929",1847,1
213,"Satow, Ernest Mason, 1843-1929",1848,1
214,"Satow, Ernest Mason, 1843-1929",1852,1
215,"Satow, Ernest Mason, 1843-1929",1853,3
216,"Satow, Ernest Mason, 1843-1929",1855,1
217,"Satow, Ernest Mason, 1843-1929",1858,1
218,"Satow, Ernest Mason, 1843-1929",1860,7
219,"Satow, Ernest Mason, 1843-1929",1861,2
220,"Satow, Ernest Mason, 1843-1929",1862,1
221,"Satow, Ernest Mason, 1843-1929",1863,1
222,"Satow, Ernest Mason, 1843-1929",1865,4
223,"Satow, Ernest Mason, 1843-1929",1868,2
224,"Satow, Ernest Mason, 1843-1929",1870,1
225,"Satow, Ernest Mason, 1843-1929",1872,1
226,"Satow, Ernest Mason, 1843-1929",1873,2
227,"Satow, Ernest Mason, 1843-1929",1874,1
228,"Satow, Ernest Mason, 1843-1929",1878,4
229,"Siebold, Heinrich von, 1852-1908",,9
230,"Siebold, Heinrich von, 1852-1908",1001,1
231,"Siebold, Heinrich von, 1852-1908",1603,1
232,"Siebold, Heinrich von, 1852-1908",1650,1
233,"Siebold, Heinrich von, 1852-1908",1686,1
234,"Siebold, Heinrich von, 1852-1908",1793,1
235,"Siebold, Heinrich von, 1852-1908",1799,1
236,"Siebold, Heinrich von, 1852-1908",1801,1
237,"Siebold, Heinrich von, 1852-1908",1815,1
238,"Siebold, Heinrich von, 1852-1908",1816,1
239,"Siebold, Heinrich von, 1852-1908",1817,2
240,"Siebold, Heinrich von, 1852-1908",1821,1
241,"Siebold, Heinrich von, 1852-1908",1826,1
242,"Siebold, Heinrich von, 1852-1908",1841,1
243,"Siebold, Heinrich von, 1852-1908",1853,1
244,"Siebold, Heinrich von, 1852-1908",1868,1

# 人毎に、刊行年を世紀でまとめてみる

In [29]:
df0 = pd.DataFrame(result)
df0

                                                  name    title origdate
0                     Aston, William George, 1841-1911     平家物語
1                       Satow, Ernest Mason, 1843-1929     平家物語
2                     Aston, William George, 1841-1911   詞のやちくさ     1798
3                       Satow, Ernest Mason, 1843-1929   詞のやちくさ     1798
4    Lockhart, James H. Stewart (James Haldane Stew...      武備志     1664
..                                                 ...      ...      ...
602                   Aston, William George, 1841-1911   県居雑録補抄     1812
603                     Satow, Ernest Mason, 1843-1929   県居雑録補抄     1812
604                   Aston, William George, 1841-1911  ゑ入江戸大絵図     1688
605                   Aston, William George, 1841-1911     伊勢物語
606                   Aston, William George, 1841-1911   原田次郎種直     1671

[607 rows x 3 columns]

In [30]:
df0["century"] = (((pd.to_numeric(df0["origdate"], errors="coerce") - 1) / 100) + 1).apply(np.floor).astype("Int64")

In [31]:
flag = df0["century"].isna()

In [32]:
df0["century"] = df0["century"].astype(str)

In [33]:
df0["century"] = df0["century"].where(flag, df0["century"] + "世紀")
df0["century"] = df0["century"].mask(flag, "")

In [34]:
df0

,name,title,origdate,century
0,"Aston, William George, 1841-1911",平家物語,,
1,"Satow, Ernest Mason, 1843-1929",平家物語,,
2,"Aston, William George, 1841-1911",詞のやちくさ,1798,18世紀
3,"Satow, Ernest Mason, 1843-1929",詞のやちくさ,1798,18世紀
4,"Lockhart, James H. Stewart (James Haldane Stew...",武備志,1664,17世紀
...,...,...,...,...
602,"Aston, William George, 1841-1911",県居雑録補抄,1812,19世紀
603,"Satow, Ernest Mason, 1843-1929",県居雑録補抄,1812,19世紀
604,"Aston, William George, 1841-1911",ゑ入江戸大絵図,1688,17世紀
605,"Aston, William George, 1841-1911",伊勢物語,,
606,"Aston, William George, 1841-1911",原田次郎種直,1671,17世紀

In [35]:
df1 = df0.groupby(["name", "century"])["century"].count().reset_index(name="count")
df1

                                                 name century  count
0                    Aston, William George, 1841-1911             92
1                    Aston, William George, 1841-1911    16世紀      2
2                    Aston, William George, 1841-1911    17世紀     66
3                    Aston, William George, 1841-1911    18世紀     77
4                    Aston, William George, 1841-1911    19世紀    100
5                                     Ceadel, Eric B.     8世紀      1
6                            Hawley, Frank, 1906-1961    13世紀      1
7   Lockhart, James H. Stewart (James Haldane Stew...              9
8   Lockhart, James H. Stewart (James Haldane Stew...    17世紀      3
9   Lockhart, James H. Stewart (James Haldane Stew...    18世紀      8
10  Lockhart, James H. Stewart (James Haldane Stew...    19世紀     17
11  Lockhart, James H. Stewart (James Haldane Stew...    20世紀      1
12                                    Minns, Ellis H.    16世紀      1
13                   Morikawa, Kanʼichirō, 1887-1980    13世紀      1
14                     Satow, Ernest Mason, 1843-1929             65
15                     Satow, Ernest Mason, 1843-1929    17世紀     32
16                     Satow, Ernest Mason, 1843-1929    18世紀     39
17                     Satow, Ernest Mason, 1843-1929    19世紀     67
18                   Siebold, Heinrich von, 1852-1908              9
19                   Siebold, Heinrich von, 1852-1908    11世紀      1
20                   Siebold, Heinrich von, 1852-1908    17世紀      3
21                   Siebold, Heinrich von, 1852-1908    18世紀      2
22                   Siebold, Heinrich von, 1852-1908    19世紀     10

In [36]:
print(df1.to_csv())

,name,century,count
0,"Aston, William George, 1841-1911",,92
1,"Aston, William George, 1841-1911",16世紀,2
2,"Aston, William George, 1841-1911",17世紀,66
3,"Aston, William George, 1841-1911",18世紀,77
4,"Aston, William George, 1841-1911",19世紀,100
5,"Ceadel, Eric B.",8世紀,1
6,"Hawley, Frank, 1906-1961",13世紀,1
7,"Lockhart, James H. Stewart (James Haldane Stewart), Sir, 1858-1937",,9
8,"Lockhart, James H. Stewart (James Haldane Stewart), Sir, 1858-1937",17世紀,3
9,"Lockhart, James H. Stewart (James Haldane Stewart), Sir, 1858-1937",18世紀,8
10,"Lockhart, James H. Stewart (James Haldane Stewart), Sir, 1858-1937",19世紀,17
11,"Lockhart, James H. Stewart (James Haldane Stewart), Sir, 1858-1937",20世紀,1
12,"Minns, Ellis H.",16世紀,1
13,"Morikawa, Kanʼichirō, 1887-1980",13世紀,1
14,"Satow, Ernest Mason, 1843-1929",,65
15,"Satow, Ernest Mason, 1843-1929",17世紀,32
16,"Satow, Ernest Mason, 1843-1929",18世紀,39
17,"Satow, Ernest Mason, 1843-1929",19世紀,67
18,"Siebold, Heinrich von, 1852-1908",,9
19,"Siebold, Heinrich von, 1852-1908",11世紀,1
20,"Siebold, Heinrich von, 1852-1908",17世紀,3
21,"Siebold, Heinrich von, 1852-1908",18世紀,2
22,"Siebold, Heinrich von, 1852-1908",19世紀,10